mystr="Amit is Good Boy"
print(mystr)
print(len(mystr))
print(mystr[2])
print(mystr[0])
print(mystr[0:10])
print(mystr[0:77])
# print(mystr[77]) # Error
print(mystr[0:16:2])
print(mystr[:])
print(mystr[::])
print(mystr[:8])
print(mystr[3:])
print(mystr[::2])
print(mystr[::99])
print(mystr.isalpha())
print(mystr.isalnum())
print(mystr.endswith("Boy"))
print(mystr.capitalize())
print(mystr.islower())
print(mystr.isupper())
print(mystr.replace("is", "are"))
print(mystr.count("o"))
